### PR TITLE
Changed the Vault backend name to the expected

### PR DESCRIPTION
**Pull request by jacobcrawford**
Kyverno has a policy that only allows "vault-backend" as the ClusterSecretStore

**Description of your changes:**

Checklist:

* [x] I have bumped the chart version
* [x] I have documented my changes if this is needed
* [x] I have described my changes in the "description of your changes" field
* [x] I have tested this change on a running cluster and the Argocd dashboard shows healthy and synced
* [ ] I have created the necessary tests in the chart, if they are possible/necessary
* [x] I have squashed commits if necessary

### CODE REVIEW

**Review by MadsHT — CHANGES_REQUESTED** [review]
This is done via patching in a kustomization in our fleet repo
https://dev.azure.com/energinet/Team%20DT/_git/flux-fleet-repo?path=/tenants/base/singularity/sync.yaml&version=GBmaster&line=23&lineEnd=60&lineStartColumn=1&lineEndColumn=1&lineStyle=plain&_a=contents

**Comment by jacobcrawford** [comment]
arh I see 😄 Though this makes it hard to do manual testing of the tenant-base helm chart. Do you know if it is possible to do this in Kyverno on all namespaces that are prefixed with "tenant", so that we do not have to make this kustomization for all our new tenants and we are able to test the helm chart manually? 😄

**Comment by MadsHT** [comment]
I will send you to my secrets manager Mr. @klausenbusk

**Comment by MadsHT** [comment]
> arh I see 😄 Though this makes it hard to do manual testing of the tenant-base helm chart. Do you know if it is possible to do this in Kyverno on all namespaces that are prefixed with "tenant", so that we do not have to make this kustomization for all our new tenants and we are able to test the helm chart manually? 😄

Just FYI, There was a time where this could be changed with the values.yaml file, using default values, but that was changed at the request of this comment [helm-charts#399](https://github.com/distributed-technologies/helm-charts/pull/399/files#r1027628776) :)

**Comment by klausenbusk** [comment]
It was implemented as a post-render to avoid a coupling between the chart and how `ClusterSecretStore` is named in the fleet-repo... Should we just make it configurable again?

**Comment by jacobcrawford** [comment]
I think we should let Kyverno do the patching or mutation to have a singlae place where we handle it and not a patch in every tenant namespace 😄 Though that seems like a new improvement and i will create a US for it, then we can discuss it at a refinement. This PR is obviously not a bugfix as there is not bug, so i will just close it 😄

**Pull request closed without merging**
