### PR TITLE
Run KubeLinter on changed charts

### PR DESCRIPTION
**Pull request by skovbakke**
KubeLinter does static analysis of the helm charts. Warnings include configurations that are not following kubernetes best practices. I think this would be a good addition to our linting. Currently it is using the default configuration which we can edit later in case we have more specific needs.

It only runs on charts that are changed in the PR.

See [KubeLinter](https://docs.kubelinter.io/#/).

**Description of your changes:**

Checklist:

* [ ] I have bumped the chart version
* [x] I have documented my changes if this is needed
* [x] I have described my changes in the "description of your changes" field
* [ ] I have tested this change on a running cluster and the Argocd dashboard shows healthy and synced
* [x] I have created the necessary tests in the chart, if they are possible/necessary
* [x] I have squashed commits if necessary

### CODE REVIEW

**Comment by klausenbusk** [comment]
What kind of issues can it find? and is there any issues with the existing charts?

**Comment by skovbakke** [comment]
A full list of the checks it can make can be found [here](https://docs.kubelinter.io/#/generated/checks). Below I have listed the ones enabled by default. As an example, currently the `ntp` chart fails the "no-read-only-root-fs" check:
* dangling-service: Indicates when services do not have any associated deployments
* deprecated-service-account-field: Indicates when deployments use the deprecated serviceAccount field
* docker-sock: Alert on deployments with docker.sock mounted in containers
* drop-net-raw-capability: Indicates when containers do not drop NET_RAW capability
* env-var-secret: Indicates when objects use a secret in an environment variable
* host-ipc: Alert on pods/deployment-likes with sharing host's IPC namespace
* host-network: Alert on pods/deployment-likes with sharing host's network namespace
* host-pid: Alert on pods/deployment-likes with sharing host's process namespace
* latest-tag: Indicates when a deployment-like object is running a container with an invalid container image
* mismatching-selector: Indicates when deployment selectors fail to match the pod template labels
* no-anti-affinity: Indicates when deployments with multiple replicas fail to specify inter-pod anti-affinity, to ensure that the orchestrator attempts to schedule replicas on different nodes
* no-extensions-v1beta: Indicates when objects use deprecated API versions under extensions/v1beta
* no-read-only-root-fs: Indicates when containers are running without a read-only root filesystem
* non-existent-service-account: Indicates when pods reference a service account that is not found
* privilege-escalation-container: Alert on containers of allowing privilege escalation that could gain more privileges than its parent process
* privileged-container: Indicates when deployments have containers running in privileged mode
* run-as-non-root: Indicates when containers are not set to runAsNonRoot
* sensitive-host-mounts: Alert on deployments with sensitive host system directories mounted in containers
* ssh-port: Indicates when deployments expose port 22, which is commonly reserved for SSH access
* unsafe-sysctls: Alert on deployments specifying unsafe sysctls that may lead to severe problems like wrong behavior of containers
* unset-cpu-requirements: Indicates when containers do not have CPU requests and limits set
* unset-memory-requirements: Indicates when containers do not have memory requests and limits set

**Review by klausenbusk — DISMISSED** [review]
Fixing the charts as we get to them SGTM.

Perhaps we should track it somewhere?

I assume we can disable the checks if needed.

**Comment by skovbakke** [comment]
Yes, we can enable/disable each check individually. It is also possible to enable additional checks that are not default.

**Review by klausenbusk — APPROVED** [review]
LGTM 🎉

**Pull request merged**
